{% set name = "enchant" %}
{% set version = "2.3.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/AbiWord/{{ name }}/releases/download/v{{ version }}/enchant-{{ version }}.tar.gz
  sha256: ce9ba47fd4d34031bd69445598a698a6611602b2b0e91d705e91a6f5099ead6e

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('enchant', max_pin='x.x') }}

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - glib
    - hunspell
  run:
    - glib
    - hunspell

test:
  commands:
    - enchant-2 -v  # [unix]

about:
  home: https://abiword.github.io/enchant/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LIB
  summary: enchant spellchecking library

extra:
  recipe-maintainers:
    - izahn
