{% set name = "enchant" %}
{% set version = "2.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/AbiWord/{{ name }}/releases/download/v{{ version }}/enchant-{{ version }}.tar.gz
  sha256: 1f7e26744db1c9a0fea61d2169f4e5c1ce435cf8c2731c37e3e4054119e994a0

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('enchant', max_pin='x.x') }}

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - groff  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - glib
    - hunspell
  run:
    - glib
    - hunspell
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - enchant-2 -v  # [unix]

about:
  home: https://abiword.github.io/enchant/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LIB
  summary: enchant spellchecking library

extra:
  recipe-maintainers:
    - izahn
